"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class aroundfeet_map_t(object):
    __slots__ = ["aroundfeet_map"]

    __typenames__ = ["float"]

    __dimensions__ = [[36]]

    def __init__(self):
        self.aroundfeet_map = [ 0.0 for dim0 in range(36) ]

    def encode(self):
        buf = BytesIO()
        buf.write(aroundfeet_map_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>36f', *self.aroundfeet_map[:36]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != aroundfeet_map_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return aroundfeet_map_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = aroundfeet_map_t()
        self.aroundfeet_map = struct.unpack('>36f', buf.read(144))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if aroundfeet_map_t in parents: return 0
        tmphash = (0x21de329d9b97f9fd) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if aroundfeet_map_t._packed_fingerprint is None:
            aroundfeet_map_t._packed_fingerprint = struct.pack(">Q", aroundfeet_map_t._get_hash_recursive([]))
        return aroundfeet_map_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

